/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessoPendenteRouteImport } from './routes/acesso-pendente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalistaRouteRouteImport } from './routes/_authenticated/analista/route'
import { Route as AuthenticatedAnalistaIndexRouteImport } from './routes/_authenticated/analista/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPendenteRoute = AcessoPendenteRouteImport.update({
  id: '/acesso-pendente',
  path: '/acesso-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalistaRouteRoute =
  AuthenticatedAnalistaRouteRouteImport.update({
    id: '/analista',
    path: '/analista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalistaIndexRoute =
  AuthenticatedAnalistaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalistaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/auth': typeof AuthRoute
  '/analista': typeof AuthenticatedAnalistaRouteRouteWithChildren
  '/analista/': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRoutesByTo {
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/analista': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/analista': typeof AuthenticatedAnalistaRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analista/': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acesso-pendente' | '/auth' | '/analista' | '/analista/'
  fileRoutesByTo: FileRoutesByTo
  to: '/acesso-pendente' | '/auth' | '/' | '/analista'
  id:
    | '__root__'
    | '/_authenticated'
    | '/acesso-pendente'
    | '/auth'
    | '/_authenticated/analista'
    | '/_authenticated/'
    | '/_authenticated/analista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoPendenteRoute: typeof AcessoPendenteRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-pendente': {
      id: '/acesso-pendente'
      path: '/acesso-pendente'
      fullPath: '/acesso-pendente'
      preLoaderRoute: typeof AcessoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analista': {
      id: '/_authenticated/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AuthenticatedAnalistaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analista/': {
      id: '/_authenticated/analista/'
      path: '/'
      fullPath: '/analista/'
      preLoaderRoute: typeof AuthenticatedAnalistaIndexRouteImport
      parentRoute: typeof AuthenticatedAnalistaRouteRoute
    }
  }
}

interface AuthenticatedAnalistaRouteRouteChildren {
  AuthenticatedAnalistaIndexRoute: typeof AuthenticatedAnalistaIndexRoute
}

const AuthenticatedAnalistaRouteRouteChildren: AuthenticatedAnalistaRouteRouteChildren =
  {
    AuthenticatedAnalistaIndexRoute: AuthenticatedAnalistaIndexRoute,
  }

const AuthenticatedAnalistaRouteRouteWithChildren =
  AuthenticatedAnalistaRouteRoute._addFileChildren(
    AuthenticatedAnalistaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalistaRouteRoute: typeof AuthenticatedAnalistaRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalistaRouteRoute: AuthenticatedAnalistaRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoPendenteRoute: AcessoPendenteRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
