/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessoPendenteRouteImport } from './routes/acesso-pendente'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalistaRouteRouteImport } from './routes/_authenticated/analista/route'
import { Route as AuthenticatedAnalistaIndexRouteImport } from './routes/_authenticated/analista/index'
import { Route as ApiPublicBackupRouteImport } from './routes/api/public/backup'
import { Route as ApiPublicBackupsRouteImport } from './routes/api/public/backups'
import { Route as ApiPublicRestaurarRouteImport } from './routes/api/public/restaurar'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPendenteRoute = AcessoPendenteRouteImport.update({
  id: '/acesso-pendente',
  path: '/acesso-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalistaRouteRoute =
  AuthenticatedAnalistaRouteRouteImport.update({
    id: '/analista',
    path: '/analista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalistaIndexRoute =
  AuthenticatedAnalistaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalistaRouteRoute,
  } as any)
const ApiPublicBackupRoute = ApiPublicBackupRouteImport.update({
  id: '/api/public/backup',
  path: '/api/public/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupsRoute = ApiPublicBackupsRouteImport.update({
  id: '/api/public/backups',
  path: '/api/public/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRestaurarRoute = ApiPublicRestaurarRouteImport.update({
  id: '/api/public/restaurar',
  path: '/api/public/restaurar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/analista': typeof AuthenticatedAnalistaRouteRouteWithChildren
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/backups': typeof ApiPublicBackupsRoute
  '/api/public/restaurar': typeof ApiPublicRestaurarRoute
  '/analista/': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRoutesByTo {
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/backups': typeof ApiPublicBackupsRoute
  '/api/public/restaurar': typeof ApiPublicRestaurarRoute
  '/analista': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/_authenticated/analista': typeof AuthenticatedAnalistaRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/backups': typeof ApiPublicBackupsRoute
  '/api/public/restaurar': typeof ApiPublicRestaurarRoute
  '/_authenticated/analista/': typeof AuthenticatedAnalistaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-pendente'
    | '/alterar-senha'
    | '/auth'
    | '/analista'
    | '/api/public/backup'
    | '/api/public/backups'
    | '/api/public/restaurar'
    | '/analista/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acesso-pendente'
    | '/alterar-senha'
    | '/auth'
    | '/'
    | '/api/public/backup'
    | '/api/public/backups'
    | '/api/public/restaurar'
    | '/analista'
  id:
    | '__root__'
    | '/_authenticated'
    | '/acesso-pendente'
    | '/alterar-senha'
    | '/auth'
    | '/_authenticated/analista'
    | '/_authenticated/'
    | '/api/public/backup'
    | '/api/public/backups'
    | '/api/public/restaurar'
    | '/_authenticated/analista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoPendenteRoute: typeof AcessoPendenteRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  AuthRoute: typeof AuthRoute
  ApiPublicBackupRoute: typeof ApiPublicBackupRoute
  ApiPublicBackupsRoute: typeof ApiPublicBackupsRoute
  ApiPublicRestaurarRoute: typeof ApiPublicRestaurarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-pendente': {
      id: '/acesso-pendente'
      path: '/acesso-pendente'
      fullPath: '/acesso-pendente'
      preLoaderRoute: typeof AcessoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analista': {
      id: '/_authenticated/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AuthenticatedAnalistaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analista/': {
      id: '/_authenticated/analista/'
      path: '/'
      fullPath: '/analista/'
      preLoaderRoute: typeof AuthenticatedAnalistaIndexRouteImport
      parentRoute: typeof AuthenticatedAnalistaRouteRoute
    }
    '/api/public/backup': {
      id: '/api/public/backup'
      path: '/api/public/backup'
      fullPath: '/api/public/backup'
      preLoaderRoute: typeof ApiPublicBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backups': {
      id: '/api/public/backups'
      path: '/api/public/backups'
      fullPath: '/api/public/backups'
      preLoaderRoute: typeof ApiPublicBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/restaurar': {
      id: '/api/public/restaurar'
      path: '/api/public/restaurar'
      fullPath: '/api/public/restaurar'
      preLoaderRoute: typeof ApiPublicRestaurarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalistaRouteRouteChildren {
  AuthenticatedAnalistaIndexRoute: typeof AuthenticatedAnalistaIndexRoute
}

const AuthenticatedAnalistaRouteRouteChildren: AuthenticatedAnalistaRouteRouteChildren =
  {
    AuthenticatedAnalistaIndexRoute: AuthenticatedAnalistaIndexRoute,
  }

const AuthenticatedAnalistaRouteRouteWithChildren =
  AuthenticatedAnalistaRouteRoute._addFileChildren(
    AuthenticatedAnalistaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalistaRouteRoute: typeof AuthenticatedAnalistaRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalistaRouteRoute: AuthenticatedAnalistaRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoPendenteRoute: AcessoPendenteRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  AuthRoute: AuthRoute,
  ApiPublicBackupRoute: ApiPublicBackupRoute,
  ApiPublicBackupsRoute: ApiPublicBackupsRoute,
  ApiPublicRestaurarRoute: ApiPublicRestaurarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
